application: travelling-planner
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: travelling-planner.application

libraries:
- name: jinja2
  version: latest